undefine([AC_SYS_LARGEFILE])
undefine([AC_FUNC_FSEEKO])
undefine([AC_FUNC_MKTIME])
sinclude(arch.m4)dnl
sinclude(gettext.m4)dnl
sinclude(jm-mktime.m4)dnl
sinclude(largefile.m4)dnl
sinclude(lcmessage.m4)dnl
sinclude(progtest.m4)dnl
sinclude(socket.m4)dnl
sinclude(strtod.m4)dnl
sinclude(regex.m4)dnl
